// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = {
  auth: {
    signUp: async () => ({ data: { user: { id: 'demo' } }, error: null }),
    signInWithPassword: async () => ({ error: null }),
    signOut: async () => {},
    onAuthStateChange: (cb) => ({ data: { subscription: { unsubscribe: () => {} } } }),
  },
  from: () => ({
    select: () => ({
      eq: () => ({
        single: () => ({ data: null }),
        update: () => ({ error: null })
      })
    })
  })
} as any;
